### ISSUE TITLE
Hpatches

### ISSUE THREAD

**Issue by ZhHaoH** [cvg/GlueStick#10]
Hi author, I would like to ask what training set the weights provided in github? I used the weights provided in github to test on the Hpatches dataset and found that it did not match very well in images with Viewpoint, may I ask what dataset you used to train the weights for testing on the Hpatches dataset?

**Comment by rpautrat** [comment]
The weights we provide were pre-trained on images from the 1M distractor images of https://github.com/filipradenovic/revisitop, then fine-tuned on MegaDepth.

Do you have examples of pairs of images of HPatches where it does not work so well? It should have a decent performance there, except for images with large rotations (eg > 45 degrees).

**Comment by ZhHaoH** [comment]
I tested that in the v_boat case of Hpatches, image 1 doesn't match image 5 very well, they happen to be largely rotated

**Comment by rpautrat** [comment]
Yes, image 5 has almost a 90 degrees rotation compared to image 1. GlueStick was only trained for small rotations, so it cannot cope with such big rotations. When you know that your application will have rotation, you can always rotate one of the two images by 90 degrees several times and match the first image with the second one rotated at 0, 90, 180 and 270 degrees.

**Comment by ZhHaoH** [comment]
Ok, I will go and try to do some rotation pre-processing, thanks for your patience
