### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ccy-ustb** [cvg/GlueStick#11]
Hello, great job!

Can your method match the extracted line segments? For example, I have already obtained line segments from two images using LSD or other line detector. Can you use your method for line matching next?That is, I simply want to match the extracted line segments.

Looking forward to your reply very much！

**Comment by rpautrat** [comment]
Hi, yes it can do that.

To do so, you need to add your existing lines in the data fed to the network. For example, in https://github.com/cvg/GlueStick/blob/40d71d5f4adc7f4fccae4cd7675a49daee3e873e/gluestick/run.py#L61, you need to add six fields in the dictionary: a tensor with key 'lines0' of shape [n_lines, 2, 2] (lines are in x-y coordinate convention), a tensor 'line_scores0' of shape [n_lines] that contains the scores of each line segment, and a bool tensor 'valid_lines0' of size [n_lines] (if all your lines are valid, just set it to True everywhere). Then add the same for the second image with 'lines1', 'line_scores1', and 'valid_lines1'. Ideally, the lines and line_scores should be sorted by decreasing line scores.

If your method does not return a line score, you could use the square root of the length of line segments for example, this usually works well.

Let me know if you encounter any issue.

**Comment by ogencoglu** [comment]
I am also interested in this. So does the number of lines of the first tensor has to be the same as the second? In your paper, you mention you utilize Hungarian algorithm for matching. So that is happening at some point after this line 61?

**Comment by rpautrat** [comment]
No, you can have a different number of lines between the two images.

We use an approximation of the Hungarian algorithm, through double softmax. This happens indeed inside the code and is called after this line 61.
