### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by TuanTNG** [cvg/GlueStick#12]
Hi,
Thank you for your excellent work.

Can you compare the fps of your model and LoFTR?

I am looking forward to hearing from you.

**Comment by rpautrat** [comment]
Hi,

It depends on several factors, such as the image resolution and number of features. I tested both methods on images of a max side of 800 pixels and a maximum of 2000 features (points + line endpoints) in GlueStick.

With the same GPU, LoFTR ran in 130ms on average, while the full inference of GlueStick (SuperPoint + LSD + GlueStick) ran in 200ms. The matching part of GlueStick only took 52ms, and most of the time was actually spent in the LSD detection. By using more efficient feature extractors, the full pipeline could thus easily run under 100ms.

**Comment by TuanTNG** [comment]
Hi @rpautrat,
Thank you for your information.
