### ISSUE TITLE
About FPS and real-time performance

### ISSUE THREAD

**Issue by yiyihao2000** [cvg/GlueStick#13]
Hey!Your work is amazing! I now have a question, which is how much fps can your model achieve when running a live demo? Is it real-time? Is your demo video processed offline and then combined into a video after each frame, or is it processed in real time? As a beginner, look forward to your answer, thank you very much!

**Comment by rpautrat** [comment]
Hi, please see a similar answer in a previous issue: https://github.com/cvg/GlueStick/issues/12#issuecomment-1577032021

The model is not real-time for now, and the video was processed offline as you described. But we are working on more efficient features (both points and lines), as well as more efficient matchers, so we hope to offer something real-time in the future.

**Comment by yiyihao2000** [comment]
> 嗨，请在上一期中看到类似的答案：[#12（评论）](https://github.com/cvg/GlueStick/issues/12#issuecomment-1577032021)
> 
> 该模型目前不是实时的，视频已如您所描述的那样离线处理。但是我们正在开发更高效的功能（点和线），以及更高效的匹配器，因此我们希望将来提供实时功能。
Thank you very much for your answer！

**Comment by yiyihao2000** [comment]
> 嗨，请在上一期中看到类似的答案：[#12（评论）](https://github.com/cvg/GlueStick/issues/12#issuecomment-1577032021)
> 
> 该模型目前不是实时的，视频已如您所描述的那样离线处理。但是我们正在开发更高效的功能（点和线），以及更高效的匹配器，因此我们希望将来提供实时功能。

Thank you very much for your answer！
