### ISSUE TITLE
Question about reprojection error

### ISSUE THREAD

**Issue by HJoonKwon** [cvg/GlueStick#17]
I have a question for the re-projection error presented on the paper. It's mentioned on the paper that the authors followed SuperGlue to calculate the re-projection error.
Can I assume that you guys used [SED](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/utils.py#L355) to compute the Area Under the Curve (AUC)
of the re-projection error of the four image corners? 

Thank you.

**Comment by rpautrat** [comment]
Hi, if you are talking about the homography experiment on HPatches, we used the reprojection error of the four image corners, as in SuperGlue.

The piece of code that you linked refers to an epipolar error, which is for real camera pose changes, not for homographies.

**Comment by HJoonKwon** [comment]
> Hi, if you are talking about the homography experiment on HPatches, we used the reprojection error of the four image corners, as in SuperGlue.
> 
> The piece of code that you linked refers to an epipolar error, which is for real camera pose changes, not for homographies.

Ahh, I see. Then the reprojection error on the paper measures the Euclidean distance between the GT corner points and the estimated corner points that are mapped using the estimated homography? Thank you for the kind answer :)

**Comment by rpautrat** [comment]
Yes, exactly!
