### ISSUE TITLE
How to get the Homography based on point-only, line-only or points+lines matches  separately？

### ISSUE THREAD

**Issue by lin-name** [cvg/GlueStick#2]
Hi, professor. 
This is a great work！Your architecture is so smart! 
I am learning your paper and code right now，and successfully execute the python scripts **run.py**, it can get the points& lines detected and matches correspondingly, but how can i get the Homography of **-img1** and **-img2** based on point-only, line-only or points+lines matches separately?  Can i get the Homography just use your scripts in this repository? or i need to use any other Algorithms like **SuperGlue** ?

Thank you very much.

**Comment by rpautrat** [comment]
Hi, we used the following repository to obtain a homography from either point-only, line-only or point+line matches: https://github.com/rpautrat/homography_est/. The file [run_hest_test.py](https://github.com/rpautrat/homography_est/blob/main/run_hest_test.py) provides an example on how to use it.
