### ISSUE TITLE
There is no setup.py for "pip install -e ."

### ISSUE THREAD

**Issue by pct0427** [cvg/GlueStick#23]
Hi,
When I try to follow the installation steps, I encounter a problem where 'pip install -e .' cannot find the setup.py file. How should I resolve this issue?

**ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /com.docker.devenvironments.code/GlueStick
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)**

thank you.

pct0427

**Comment by MikeJPelton** [comment]
Have just encountered the same issue trying to build this in a conda environment. Installing python fixed it for me, e.g.
```
conda install python=3.8
```
After this, running the pip install step ran. Hope it helps!

**Comment by pct0427** [comment]
> Have just encountered the same issue trying to build this in a conda environment. Installing python fixed it for me, e.g.
> 
> ```
> conda install python=3.8
> ```
> 
> After this, running the pip install step ran. Hope it helps!

Got it and thanks, bro.

**Comment by c-keil** [comment]
Upgrading pip can also solve this issue. `pip install --upgrade pip`
