### ISSUE TITLE
gluestick with deeplsd

### ISSUE THREAD

**Issue by fatih4d** [cvg/GlueStick#26]
How can i use gluestick with deeplsd ?

**Comment by rpautrat** [comment]
Hi, I recommend you to use the [GlueFactory ](https://github.com/cvg/glue-factory/tree/main)repository for this. This is the training code code repository for GlueStick. There is already the possibility to use DeepLSD there. You can take the [existing config](https://github.com/cvg/glue-factory/blob/main/gluefactory/configs/superpoint%2Blsd%2Bgluestick.yaml) file to use SuperPoint+LSD+GlueStick, and change the line "name: gluefactory.models.lines.lsd" with "name: gluefactory.models.lines.deeplsd".
