### ISSUE TITLE
The features cannot be matched in the reverse image

### ISSUE THREAD

**Issue by Jinunmeng** [cvg/GlueStick#27]
Great job! I've some issues while working with aerial images for feature matching.

When the images are captured in the same orientation, feature matching works fine. However, when images are captured in the reverse orientation, the features cannot be matched

![point_matches](https://github.com/cvg/GlueStick/assets/13739181/5bf6e7f6-fa2e-424a-bb0f-4e0b9e493388)

any advice on this? thank you

**Comment by rpautrat** [comment]
Hi, GlueStick is based on SuperPoint, which has been trained for rotations up to 45 degrees. So it is not meant to work on larger rotations. The simplest fix in your case is to try the 4 rotations 0, 90, 180, 270 degrees, try to match each time, and keep the rotation that produced the most matches.
