### ISSUE TITLE
training

### ISSUE THREAD

**Issue by shy922** [cvg/GlueStick#3]
Hi,When will the training code be published？

**Comment by rpautrat** [comment]
Hi, probably in the next few weeks. We are currently testing the cleaned training code by re-training GlueStick from scratch, and still improving it to provide the best experience. Since re-training takes almost 2 weeks, it is slowing down the release.

**Comment by shy922** [comment]
> Hi, probably in the next few weeks. We are currently testing the cleaned training code by re-training GlueStick from scratch, and still improving it to provide the best experience. Since re-training takes almost 2 weeks, it is slowing down the release.

hi,Thank you very much for your work.Do you have superpoint+superglue train code?

**Comment by rpautrat** [comment]
We have some internal code to retrain SuperGlue and we are working on version to re-train a feature detector similar to SuperPoint (which will be released when it is ready as well).

**Comment by rpautrat** [comment]
Hi, we are pleased to announce that the training code for GlueStick has been released! It is available in a different repository, [GlueFactory](https://github.com/cvg/glue-factory), within a larger framework to train deep matchers, use different feature extractors, robust estimators and provide several evaluation benchmarks. We apologize for the delayed release, and hope that you will like this new framework!
