### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by SebastienLinker** [cvg/GlueStick#36]
Hi, Thanks for this amazing project.

Can you also provide an example for filters in TwoViewPipelines objects? https://github.com/cvg/GlueStick/blob/main/gluestick/models/two_view_pipeline.py#L69

I'm trying to filter out all the small lines but cannot find any doc to this feature.

**Comment by rpautrat** [comment]
Hi, this repo does not make use of the filters in the TwoViewPipeline.

However, if you want to filter out all small lines, you can do it in the configuration of the wireframe extractor. For example, in the demo notebook, you can change the `conf` dict by adding a new field 'min_length' specifying the minimum line length (in pixels):
```
conf = {
    'name': 'two_view_pipeline',
    'use_lines': True,
    'extractor': {
        'name': 'wireframe',
        'sp_params': {
            'force_num_keypoints': False,
            'max_num_keypoints': MAX_N_POINTS,
        },
        'wireframe_params': {
            'merge_points': True,
            'merge_line_endpoints': True,
        },
        'max_n_lines': MAX_N_LINES,
        'min_length': 15,
    },
    'matcher': {
        'name': 'gluestick',
        'weights': str(GLUESTICK_ROOT / 'resources' / 'weights' / 'checkpoint_GlueStick_MD.tar'),
        'trainable': False,
    },
    'ground_truth': {
        'from_pose_depth': False,
    }
}
```

Note that this field is set to 15 pixels by default (https://github.com/cvg/GlueStick/blob/0f28efd33ed6e43ab63760decd62750cdede5721/gluestick/models/wireframe.py#L100C10-L100C20).

**Comment by SebastienLinker** [comment]
Thanks, I did not notice this parameter
