### ISSUE TITLE
How to only use lines/points?

### ISSUE THREAD

**Issue by Mxbonn** [cvg/GlueStick#4]
It seems that the pipeline has the arguments :
`use_lines` and `use_points`. 
However they do not seem to be used as changing their values still outputs both points and lines.

**Comment by rpautrat** [comment]
Hi, you are correct that currently these two parameters are useless. They are actually used in the training code, which will be released later. So it will make sense at that time.

For now, if you want to use it with only points or only lines, you can set the parameters 'max_num_keypoints' or 'max_n_lines' to 0 in the config.

**Comment by Mxbonn** [comment]
That does the trick, thanks!
Slightly unrelated question: will you also release code on how to use it with SOLD^2 instead of LSD?

**Comment by rpautrat** [comment]
Yes, we will make it more flexible in the next release, allowing to use it with SOLD2 or even other detectors!
