### ISSUE TITLE
How to only use points?

### ISSUE THREAD

**Issue by dengzhicong123** [cvg/GlueStick#7]
Hello , sorry to bother you . I want to only use points , what modules do I need ? Is it superpoints ?

**Comment by rpautrat** [comment]
Hi, there is already an issue replying to this question: https://github.com/cvg/GlueStick/issues/4#issuecomment-1538537605
I hope this fix your issue.

**Comment by dengzhicong123** [comment]
Thank you very much again for your research results. I look forward to your early open source of the new generation version of the code. Your research results will be very helpful to the community.
