### ISSUE TITLE
How to obtain the four parameters lines0, lines1, lines_junc_idx0, lines_junc_idx1 ？

### ISSUE THREAD

**Issue by DWBSIC** [cvg/GlueStick#8]
Thank you very much for your research results. Now I have a question, and I sincerely hope that you can answer it.
I don't understand how to get these four parameters from data[]

lines0 = data['lines0'].flatten(1, 2)
lines1 = data['lines1'].flatten(1, 2)
lines_junc_idx0 = data['lines_junc_idx0'].flatten(1, 2)  # [b_size, num_lines * 2]
lines_junc_idx1 = data['lines_junc_idx1'].flatten(1, 2)

**Comment by rpautrat** [comment]
Hi, they are gathered through the [wireframe.py](https://github.com/cvg/GlueStick/blob/main/gluestick/models/wireframe.py) model, which should be called before the GlueStick model.

But the proper way to use GlueStick is to use the [two_view_pipeline](https://github.com/cvg/GlueStick/blob/main/gluestick/models/two_view_pipeline.py) model, that combines both the wireframe and gluestick models. This is what is used in the demo notebook: https://github.com/cvg/GlueStick/blob/main/gluestick_matching_demo.ipynb

**Comment by DWBSIC** [comment]
Thank you very much again for your research results. I look forward to your early open source of the new generation version of the code. Your research results will be very helpful to the community.
