### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by ZhHaoH** [cvg/GlueStick#9]
Hi, I am very interested in your research project, when you can provide the training code? And can you provide the code to generate the ground truth of the dataset?

**Comment by rpautrat** [comment]
Hi, we are still making sure that we can re-train GlueStick and obtain similar results as the released model with our cleaned training code. But it will be released soon (probably in the next two weeks), together with the ground truth generation.

**Comment by ZhHaoH** [comment]
Thank you very much. If it could be released in two weeks, it would be really exciting news~

**Comment by ZhHaoH** [comment]
Hello, when will the training code be released?

**Comment by rpautrat** [comment]
Hi, there are some updates regarding the release of the training code, which will unfortunately be delayed. To give more context, we are planning to release a full framework to retrain not only GlueStick, but also SuperGlue and similar works. One of these other works requires additional time to clean and test the code, and so the framework will not be released before that time.
We hope to release everything in a few weeks / months.

**Comment by ZhHaoH** [comment]
Well, you have done a great job, so we all hope to see the training code soon!

**Comment by ZhHaoH** [comment]
May I ask if the training code and code for generating the ground truth dataset will be provided in the near future? I apologize for asking this question again, but I am really eager to obtain them.

**Comment by rpautrat** [comment]
Hi, yes this is still planned. We are still improving a few things, and will release it during the month of August. Sorry for the delay, and thank you for your patience!

**Comment by ZhHaoH** [comment]
Ok, and congratulations on your work being accepted by ICCV2023.

**Comment by rpautrat** [comment]
Thank you!

**Comment by hoya012** [comment]
Thank you for your awesome code sharing.
Anyway, any update for training code release? i want to train GlueStick with my dataset for accurate line matching.

**Comment by rpautrat** [comment]
Hi, we are pleased to announce that the training code for GlueStick has been released! It is available in a different repository, [GlueFactory](https://github.com/cvg/glue-factory), within a larger framework to train deep matchers, use different feature extractors, robust estimators and provide several evaluation benchmarks. We apologize for the delayed release, and hope that you will like this new framework!

**Comment by hoya012** [comment]
Thank you very much!! I hope you enjoy the ICCV.
